using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Windows.Foundation
{
	/// <summary>
	/// Represents a method that handles general events.
	/// </summary>
	/// <param name="sender">The object type.</param>
	/// <param name="args">The type of event data generated by the event.</param>
	public delegate void TypedEventHandler<TSender, TResult>(TSender sender, TResult args);
}
